
# Add source files here
EXECUTABLE	:= SCP 
# CUDA source files (compiled with cudacc)
CUFILES		:= scalarProd.cu
# CUDA dependency files
CU_DEPS		:= scalarProd_kernel.cu
# C/C++ source files (compiled with gcc / c++)
CCFILES		:= scalarProd_gold.cpp


################################################################################
# Rules and targets

include ../common.mk
